.TH MONITOR BITTORRENT 1
.SH NAME
dht_crawler/exec.py \- sends KRPC calls to any known host, or program should
find this host and monitor trough this start host to BitTorrent network
with help of Kademlia DHT.
.SH SYNOPSIS
.B dht_crawler/exec.py
[\fB\-h\fR]
[\fB\--help\fR]
[\fB\--hash\fR \fIinfohash\fR]
[\fB\--file\fR \fIfile [file ...]\fR]
[\fB\--magnet\fR \fIfile [file ...]\fR]
[\fB\--bind_port\fR \fIport\fR]
[\fB\--duration\fR \fIseconds\fR]
[\fB\--print_as_country\fR]
[\fB\--db_format\fR]
[\fB\--fifo\fR]
[\fB\--counter\fR \fIseconds\fR]
[\fB\--max-peers\fR \fIqueue_length\fR]
[\fB\--test\fR]
[\fB\--country\fR \fI<country-name>\fR]

.SH DESCRIPTION
.B dht_crawler \fRuses the DHT BitTorrent protocol for MLDHT. Has 4 types of messages
from which for monitoring are 2 of them used. .B dht_crawler \fRworks with IPv4. For communication and recieving
threads are used. Project is composed of modules and unit tests with integration testing.
Please read documentation for further information.
.SH OPTIONS
.TP
.BR \-h or --help\fR
Show help message.
.TP
.BR \--hash\fR \fIinfohash\fR
Use infohash for crawling.
.TP
.BR \--file\fR \fIfile [file ...]\fR
Use torrent file as input <file>. Extract all necessary information for crawling and further
information to store in database. For storing in database format use \fI--db_format\fR.
.TP
.BR \--magnet\fR \fIfile [file ...]\fR
Use torrent magnet-link as input <file>. This magnet link must be stored within file.
Also there is extraction of additional information from magnet-link.
.TP
.BR \--bind_port\fR \fIport\fR
Specifies <port> number on which UDP socket should be connected. This option is
mostly used by integration tests which are using multiple instances of crawler.
.TP
.BR \--duration\fR \fIseconds\fR
Specifies duration of crawl in <seconds>. When exhausted, all threads are killed
and resources are dealocated.
.TP
.BR \--print_as_country\fR
Formats output with use of geoip on peers.
.TP
.BR \--db_format\fR
Formats output to database format with infohash, peer pool, node pool and torrent
name if present.
.TP
.BR \--fifo\fR
Runs crawler with FIFO queue instead of LIFO. When non present LIFO queue is
created.
.TP
.BR \--counter\fR \fIseconds\fR
Counter determines in seconds how long should we wait before sending and recieving
packet. This timer is set to 0 when not present.
.TP
.BR \--max-peers\fR \fIqueue_length\fR
Specifies length of queue by integer.
.TP
.BR \--test\fR
Tests DHT connection. Used for unit testing.
.TP
.BR \--country\fR \fI<country-name>\fR
When specifies crawler should print only country with given <country-name>.
